
services:
  redis:
    image: redis:4.0.6-alpine
    restart: always
    ports:
      - "6379:6379"
  mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminuser
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  executor:
   build: ./services/executor
#   command: bash -c "while true; do echo hello; sleep 2; done"
   restart: always
   # ports:
   #   - "5001:5001"
   environment:
     STORAGE: /Executor/storage
   depends_on:
     - redis
     - mongo
     - socketio
   volumes:
     - ./storage:/Executor/storage
  server:
    build: ./services/server
    restart: always
    # ports:
    #   - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - redis
      - mongo
      - socketio
    volumes:
      - ./storage:/Server/storage
  socketio:
    build: ./services/socketIO
    restart: always
    ports:
      - '7000:7000'
    # network_mode: "host"
  webapp:
    # build: ./services/webapp
    # command: bash -c "while true; do echo hello; sleep 2; done"
    build:
      context: ./services/webapp
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./services/webapp/src:/app/src:rw
    # ports:
    #   - "4200:4200"
  nginx:
    depends_on:
      - webapp
      - server
      - socketio
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
volumes:
  storage:
