"""Generate the TypeScript copy of the shared enums for the webapp.

The webapp compares statuses and roles literally, so it needs the same values
as the Python services. Rather than a second hand-written copy (the server's
``"NOT READY"`` once drifted from the executor's ``"NOT_READY"`` and matched
nothing), the enums of :mod:`rmn_common.status` are rendered to
``services/webapp/ng/src/app/generated/rmn-contracts.ts``, committed, and
``python -m rmn_common.typescript --check`` fails in CI when the file is stale.

Usage::

    python -m rmn_common.typescript          # rewrite the file
    python -m rmn_common.typescript --check  # exit 1 when it differs
"""

from __future__ import annotations

import sys
from enum import Enum
from pathlib import Path

from rmn_common import status

# Python enum -> TypeScript enum name
ENUMS: dict[type[Enum], str] = {
    status.Job_Status: "JobStatus",
    status.Document_Status: "DocumentStatus",
    status.Output_File: "OutputFile",
    status.User_Role: "UserRole",
}

REPO = Path(__file__).resolve().parents[3]
DEFAULT_PATH = REPO / "services/webapp/ng/src/app/generated/rmn-contracts.ts"

HEADER = """\
// GENERATED by services/common/rmn_common/typescript.py from rmn_common.status.
// Do not edit: run `python -m rmn_common.typescript` in services/common.
// The values are the strings stored in MongoDB and sent by the server.
"""


def render() -> str:
    """The TypeScript source for every enum of :mod:`rmn_common.status`."""
    blocks = [HEADER]
    for enum, name in ENUMS.items():
        members = "\n".join(f"  {m.name} = '{m.value}'," for m in enum)
        blocks.append(f"export enum {name} {{\n{members}\n}}\n")
    return "\n".join(blocks)


def main(argv: list[str] | None = None) -> int:
    """Write the file, or with ``--check`` return 1 when it is out of date."""
    args = list(sys.argv[1:] if argv is None else argv)
    check = "--check" in args
    args = [a for a in args if a != "--check"]
    path = Path(args[0]) if args else DEFAULT_PATH
    expected = render()
    if check:
        current = path.read_text() if path.exists() else None
        if current != expected:
            print(f"{path} is stale: run `python -m rmn_common.typescript`")
            return 1
        print(f"{path} is up to date")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected)
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
