#!/usr/bin/env bash
#
# Generate deployment/secrets.yml (the `rmn-secrets` Secret) from
# deployment/secrets.example.yml, filling every CHANGE_ME with a random value
# exactly as the template documents (openssl rand -hex 24 / 32).
#
# Usage:
#   scripts/generate-secrets.sh                         # fresh random values
#   scripts/generate-secrets.sh --from-env .env         # reuse values from a .env
#   scripts/generate-secrets.sh --slack-token xoxb-...  # set the optional token
#   scripts/generate-secrets.sh --mongodb-user admin --output /path/secrets.yml
#
# The script NEVER overwrites: if the output file already exists it stops
# without touching it. To regenerate, move the old file away yourself first
# (and remember the Mongo root password is fixed on an existing volume).
#
# --from-env reads MONGODB_USER, MONGODB_PASSWORD, REDIS_PASSWORD, ADMIN_API_KEY,
# SLACK_TOKEN and SOCKETIO_SERVICE_TOKEN; values that are empty or "change-me"
# are generated instead. Use it when the cluster and docker-compose must share
# credentials, or when the Mongo password is already fixed on an existing
# volume (it cannot be changed by rewriting the Secret alone).
#
# The output is gitignored and written with mode 600. Apply it with:
#   kubectl apply -f deployment/secrets.yml
#
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
template="$repo_root/deployment/secrets.example.yml"
output="$repo_root/deployment/secrets.yml"

mongodb_user="adminuser"
mongodb_password=""
redis_password=""
admin_api_key=""
slack_token=""
socketio_service_token=""

usage() { sed -n '3,/^set -euo/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'; }

while [ $# -gt 0 ]; do
  case "$1" in
    --from-env)
      env_file="${2:?--from-env needs a file}"; shift 2
      [ -f "$env_file" ] || { echo "No such file: $env_file" >&2; exit 1; }
      # only export the variables we know; ignore comments/blank lines
      while IFS='=' read -r key value; do
        case "$key" in
          MONGODB_USER) [ -n "$value" ] && mongodb_user="$value" ;;
          MONGODB_PASSWORD) mongodb_password="$value" ;;
          REDIS_PASSWORD) redis_password="$value" ;;
          ADMIN_API_KEY) admin_api_key="$value" ;;
          SLACK_TOKEN) slack_token="$value" ;;
          SOCKETIO_SERVICE_TOKEN) socketio_service_token="$value" ;;
        esac
      done < <(grep -E '^[A-Z_]+=' "$env_file" | sed -e 's/^\([A-Z_]*\)="\(.*\)"$/\1=\2/' -e "s/^\([A-Z_]*\)='\(.*\)'$/\1=\2/")
      ;;
    --mongodb-user) mongodb_user="${2:?--mongodb-user needs a value}"; shift 2 ;;
    --slack-token) slack_token="${2:?--slack-token needs a value}"; shift 2 ;;
    --output) output="${2:?--output needs a path}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

[ -f "$template" ] || { echo "Template not found: $template" >&2; exit 1; }
command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

refuse_overwrite() {
  echo "Refusing to overwrite existing $output; this script never replaces a secrets file." >&2
  echo "Move it away first if you really want a new one. NOTE: on an existing Mongo" >&2
  echo "volume the root password is fixed at first init; a new Secret will NOT change it." >&2
  exit 1
}
# -e also catches a symlink/dir at that path; -L a dangling symlink
if [ -e "$output" ] || [ -L "$output" ]; then
  refuse_overwrite
fi

# treat the .env placeholders as "not set"
is_placeholder() { [ -z "$1" ] || [ "$1" = "change-me" ] || [ "$1" = "CHANGE_ME" ]; }
is_placeholder "$mongodb_password" && mongodb_password="$(openssl rand -hex 24)"
is_placeholder "$redis_password" && redis_password="$(openssl rand -hex 24)"
is_placeholder "$admin_api_key" && admin_api_key="$(openssl rand -hex 32)"
is_placeholder "$socketio_service_token" && socketio_service_token="$(openssl rand -hex 32)"
# slack-token is optional: empty disables the health-check pings
is_placeholder "$slack_token" && slack_token=""

# Keep the template's manifest (everything from apiVersion on) and substitute
# the stringData values. Values are written through printf, never through a
# sed replacement, so an arbitrary --slack-token / --mongodb-user cannot break
# the YAML; they are double-quoted with \ and " escaped.
yaml_quote() { printf '"%s"' "$(printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"; }

value_for() {
  case "$1" in
    mongodb-user) yaml_quote "$mongodb_user" ;;
    mongodb-password) yaml_quote "$mongodb_password" ;;
    redis-password) yaml_quote "$redis_password" ;;
    admin-api-key) yaml_quote "$admin_api_key" ;;
    slack-token) yaml_quote "$slack_token" ;;
    socketio-service-token) yaml_quote "$socketio_service_token" ;;
    *) return 1 ;;
  esac
}

umask 077
tmp="$(mktemp "$(dirname "$output")/.secrets.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# This file holds real credentials: it is gitignored, NEVER commit it."
  echo "# Apply with: kubectl apply -f deployment/secrets.yml"
  in_data=0
  while IFS= read -r line; do
    if [ "$in_data" -eq 1 ] && [[ "$line" =~ ^[[:space:]]{2}([a-z-]+):[[:space:]]*(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      if quoted="$(value_for "$key")"; then
        printf '  %s: %s\n' "$key" "$quoted"
      else
        # a key added to the template that this script does not know about
        echo "Template key '$key' is not handled by this script; add it." >&2
        exit 1
      fi
    else
      [ "$line" = "stringData:" ] && in_data=1
      printf '%s\n' "$line"
    fi
  done < <(sed -n '/^apiVersion:/,$p' "$template")
} > "$tmp"

if grep -q "CHANGE_ME" "$tmp"; then
  echo "Internal error: a CHANGE_ME placeholder was left in the output." >&2
  exit 1
fi
# ln(1) fails if the target exists, so the publish step is atomic AND cannot
# clobber a file created between the check above and now (mv would).
if ! ln "$tmp" "$output" 2>/dev/null; then
  refuse_overwrite
fi
rm -f "$tmp"
trap - EXIT
chmod 600 "$output"

if git -C "$repo_root" check-ignore -q "$output" 2>/dev/null; then
  ignored="gitignored"
else
  ignored="WARNING: NOT gitignored, do not commit it"
fi
echo "Wrote $output ($ignored, mode 600)."
[ -z "$slack_token" ] && echo "slack-token left empty: health-check pings disabled (use --slack-token to set it)."
echo "Next: kubectl apply -f ${output#"$repo_root/"}"
